export { i18n, SUPPORTED_LOCALES, LOCALE_STORAGE_KEY } from './i18n'
export type { Locale, Namespace } from './i18n'
export { ALL_NAMESPACES } from './i18n'
export * from './currencies'
export * from './theme'